[2023-06-16 12:37:13,248] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: postgres_dag.createtable_task manual__2023-06-16T12:37:12.918270+00:00 [queued]>
[2023-06-16 12:37:13,255] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: postgres_dag.createtable_task manual__2023-06-16T12:37:12.918270+00:00 [queued]>
[2023-06-16 12:37:13,256] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-16 12:37:13,256] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-06-16 12:37:13,256] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-16 12:37:13,266] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): createtable_task> on 2023-06-16 12:37:12.918270+00:00
[2023-06-16 12:37:13,271] {standard_task_runner.py:52} INFO - Started process 1618 to run task
[2023-06-16 12:37:13,275] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'createtable_task', 'manual__2023-06-16T12:37:12.918270+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmpu31_t1di', '--error-file', '/tmp/tmpjyoplr3b']
[2023-06-16 12:37:13,276] {standard_task_runner.py:80} INFO - Job 10: Subtask createtable_task
[2023-06-16 12:37:13,323] {task_command.py:370} INFO - Running <TaskInstance: postgres_dag.createtable_task manual__2023-06-16T12:37:12.918270+00:00 [running]> on host f97be8e8a009
[2023-06-16 12:37:13,381] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=createtable_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-16T12:37:12.918270+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-16T12:37:12.918270+00:00
[2023-06-16 12:37:13,391] {base.py:68} INFO - Using connection ID 'postgre_assign' for task execution.
[2023-06-16 12:37:13,395] {dbapi.py:213} INFO - Running statement: CREATE TABLE IF NOT EXISTS execution (
    id SERIAL PRIMARY KEY,
    exectime TIMESTAMP DEFAULT CURRENT_TIMESTAMP);, parameters: None
[2023-06-16 12:37:13,396] {postgres.py:94} INFO - NOTICE:  relation "execution" already exists, skipping

[2023-06-16 12:37:13,406] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=createtable_task, execution_date=20230616T123712, start_date=20230616T123713, end_date=20230616T123713
[2023-06-16 12:37:13,451] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-16 12:37:13,479] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
