[2023-06-16 12:37:13,951] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: postgres_dag.insert_rows_task manual__2023-06-16T12:37:12.918270+00:00 [queued]>
[2023-06-16 12:37:13,960] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: postgres_dag.insert_rows_task manual__2023-06-16T12:37:12.918270+00:00 [queued]>
[2023-06-16 12:37:13,961] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-16 12:37:13,962] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-06-16 12:37:13,962] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-16 12:37:13,976] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): insert_rows_task> on 2023-06-16 12:37:12.918270+00:00
[2023-06-16 12:37:13,981] {standard_task_runner.py:52} INFO - Started process 1628 to run task
[2023-06-16 12:37:13,987] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'postgres_dag', 'insert_rows_task', 'manual__2023-06-16T12:37:12.918270+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dag.py', '--cfg-path', '/tmp/tmp_28d_hw6', '--error-file', '/tmp/tmpuwuw16k1']
[2023-06-16 12:37:13,990] {standard_task_runner.py:80} INFO - Job 11: Subtask insert_rows_task
[2023-06-16 12:37:14,076] {task_command.py:370} INFO - Running <TaskInstance: postgres_dag.insert_rows_task manual__2023-06-16T12:37:12.918270+00:00 [running]> on host f97be8e8a009
[2023-06-16 12:37:14,162] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_dag
AIRFLOW_CTX_TASK_ID=insert_rows_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-16T12:37:12.918270+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-16T12:37:12.918270+00:00
[2023-06-16 12:37:14,175] {base.py:68} INFO - Using connection ID 'postgre_assign' for task execution.
[2023-06-16 12:37:14,182] {dbapi.py:213} INFO - Running statement: INSERT INTO execution (exectime) VALUES (CURRENT_TIMESTAMP);, parameters: None
[2023-06-16 12:37:14,184] {dbapi.py:221} INFO - Rows affected: 1
[2023-06-16 12:37:14,199] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=postgres_dag, task_id=insert_rows_task, execution_date=20230616T123712, start_date=20230616T123713, end_date=20230616T123714
[2023-06-16 12:37:14,244] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-06-16 12:37:14,278] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
